/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips/index'
import { Route as AuthenticatedTopupsIndexRouteImport } from './routes/_authenticated/topups/index'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedPromosIndexRouteImport } from './routes/_authenticated/promos/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedMembershipsIndexRouteImport } from './routes/_authenticated/memberships/index'
import { Route as AuthenticatedLockersIndexRouteImport } from './routes/_authenticated/lockers/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCreditsIndexRouteImport } from './routes/_authenticated/credits/index'
import { Route as AuthenticatedCreditsCardsIndexRouteImport } from './routes/_authenticated/credits-cards/index'
import { Route as AuthenticatedBundlesIndexRouteImport } from './routes/_authenticated/bundles/index'
import { Route as AuthenticatedAddressesIndexRouteImport } from './routes/_authenticated/addresses/index'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips/$tripId'
import { Route as AuthenticatedTicketsCreateRouteImport } from './routes/_authenticated/tickets/create'
import { Route as AuthenticatedLockersMapRouteImport } from './routes/_authenticated/lockers/map'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/_authenticated/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/_authenticated/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTopupsIndexRoute =
  AuthenticatedTopupsIndexRouteImport.update({
    id: '/_authenticated/topups/',
    path: '/topups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/_authenticated/tickets/',
    path: '/tickets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPromosIndexRoute =
  AuthenticatedPromosIndexRouteImport.update({
    id: '/_authenticated/promos/',
    path: '/promos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/_authenticated/messages/',
    path: '/messages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMembershipsIndexRoute =
  AuthenticatedMembershipsIndexRouteImport.update({
    id: '/_authenticated/memberships/',
    path: '/memberships/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLockersIndexRoute =
  AuthenticatedLockersIndexRouteImport.update({
    id: '/_authenticated/lockers/',
    path: '/lockers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/_authenticated/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/_authenticated/invoices/',
    path: '/invoices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/_authenticated/drivers/',
    path: '/drivers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/_authenticated/customers/',
    path: '/customers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCreditsIndexRoute =
  AuthenticatedCreditsIndexRouteImport.update({
    id: '/_authenticated/credits/',
    path: '/credits/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCreditsCardsIndexRoute =
  AuthenticatedCreditsCardsIndexRouteImport.update({
    id: '/_authenticated/credits-cards/',
    path: '/credits-cards/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBundlesIndexRoute =
  AuthenticatedBundlesIndexRouteImport.update({
    id: '/_authenticated/bundles/',
    path: '/bundles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAddressesIndexRoute =
  AuthenticatedAddressesIndexRouteImport.update({
    id: '/_authenticated/addresses/',
    path: '/addresses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/_authenticated/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTicketsCreateRoute =
  AuthenticatedTicketsCreateRouteImport.update({
    id: '/_authenticated/tickets/create',
    path: '/tickets/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLockersMapRoute = AuthenticatedLockersMapRouteImport.update({
  id: '/_authenticated/lockers/map',
  path: '/lockers/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/_authenticated/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/lockers/map': typeof AuthenticatedLockersMapRoute
  '/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/bundles': typeof AuthenticatedBundlesIndexRoute
  '/credits-cards': typeof AuthenticatedCreditsCardsIndexRoute
  '/credits': typeof AuthenticatedCreditsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/lockers': typeof AuthenticatedLockersIndexRoute
  '/memberships': typeof AuthenticatedMembershipsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/promos': typeof AuthenticatedPromosIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/topups': typeof AuthenticatedTopupsIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/lockers/map': typeof AuthenticatedLockersMapRoute
  '/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/bundles': typeof AuthenticatedBundlesIndexRoute
  '/credits-cards': typeof AuthenticatedCreditsCardsIndexRoute
  '/credits': typeof AuthenticatedCreditsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/lockers': typeof AuthenticatedLockersIndexRoute
  '/memberships': typeof AuthenticatedMembershipsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/promos': typeof AuthenticatedPromosIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/topups': typeof AuthenticatedTopupsIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/lockers/map': typeof AuthenticatedLockersMapRoute
  '/_authenticated/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/addresses/': typeof AuthenticatedAddressesIndexRoute
  '/_authenticated/bundles/': typeof AuthenticatedBundlesIndexRoute
  '/_authenticated/credits-cards/': typeof AuthenticatedCreditsCardsIndexRoute
  '/_authenticated/credits/': typeof AuthenticatedCreditsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/lockers/': typeof AuthenticatedLockersIndexRoute
  '/_authenticated/memberships/': typeof AuthenticatedMembershipsIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/promos/': typeof AuthenticatedPromosIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/topups/': typeof AuthenticatedTopupsIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/customers/$customerId'
    | '/lockers/map'
    | '/tickets/create'
    | '/trips/$tripId'
    | '/addresses'
    | '/bundles'
    | '/credits-cards'
    | '/credits'
    | '/customers'
    | '/drivers'
    | '/invoices'
    | '/items'
    | '/lockers'
    | '/memberships'
    | '/messages'
    | '/promos'
    | '/tickets'
    | '/topups'
    | '/trips'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/customers/$customerId'
    | '/lockers/map'
    | '/tickets/create'
    | '/trips/$tripId'
    | '/addresses'
    | '/bundles'
    | '/credits-cards'
    | '/credits'
    | '/customers'
    | '/drivers'
    | '/invoices'
    | '/items'
    | '/lockers'
    | '/memberships'
    | '/messages'
    | '/promos'
    | '/tickets'
    | '/topups'
    | '/trips'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/lockers/map'
    | '/_authenticated/tickets/create'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/addresses/'
    | '/_authenticated/bundles/'
    | '/_authenticated/credits-cards/'
    | '/_authenticated/credits/'
    | '/_authenticated/customers/'
    | '/_authenticated/drivers/'
    | '/_authenticated/invoices/'
    | '/_authenticated/items/'
    | '/_authenticated/lockers/'
    | '/_authenticated/memberships/'
    | '/_authenticated/messages/'
    | '/_authenticated/promos/'
    | '/_authenticated/tickets/'
    | '/_authenticated/topups/'
    | '/_authenticated/trips/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedLockersMapRoute: typeof AuthenticatedLockersMapRoute
  AuthenticatedTicketsCreateRoute: typeof AuthenticatedTicketsCreateRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedAddressesIndexRoute: typeof AuthenticatedAddressesIndexRoute
  AuthenticatedBundlesIndexRoute: typeof AuthenticatedBundlesIndexRoute
  AuthenticatedCreditsCardsIndexRoute: typeof AuthenticatedCreditsCardsIndexRoute
  AuthenticatedCreditsIndexRoute: typeof AuthenticatedCreditsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedLockersIndexRoute: typeof AuthenticatedLockersIndexRoute
  AuthenticatedMembershipsIndexRoute: typeof AuthenticatedMembershipsIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedPromosIndexRoute: typeof AuthenticatedPromosIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedTopupsIndexRoute: typeof AuthenticatedTopupsIndexRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/topups/': {
      id: '/_authenticated/topups/'
      path: '/topups'
      fullPath: '/topups'
      preLoaderRoute: typeof AuthenticatedTopupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/promos/': {
      id: '/_authenticated/promos/'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof AuthenticatedPromosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/memberships/': {
      id: '/_authenticated/memberships/'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lockers/': {
      id: '/_authenticated/lockers/'
      path: '/lockers'
      fullPath: '/lockers'
      preLoaderRoute: typeof AuthenticatedLockersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/credits/': {
      id: '/_authenticated/credits/'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/credits-cards/': {
      id: '/_authenticated/credits-cards/'
      path: '/credits-cards'
      fullPath: '/credits-cards'
      preLoaderRoute: typeof AuthenticatedCreditsCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bundles/': {
      id: '/_authenticated/bundles/'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof AuthenticatedBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/addresses/': {
      id: '/_authenticated/addresses/'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets/create': {
      id: '/_authenticated/tickets/create'
      path: '/tickets/create'
      fullPath: '/tickets/create'
      preLoaderRoute: typeof AuthenticatedTicketsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lockers/map': {
      id: '/_authenticated/lockers/map'
      path: '/lockers/map'
      fullPath: '/lockers/map'
      preLoaderRoute: typeof AuthenticatedLockersMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedLockersMapRoute: AuthenticatedLockersMapRoute,
  AuthenticatedTicketsCreateRoute: AuthenticatedTicketsCreateRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedAddressesIndexRoute: AuthenticatedAddressesIndexRoute,
  AuthenticatedBundlesIndexRoute: AuthenticatedBundlesIndexRoute,
  AuthenticatedCreditsCardsIndexRoute: AuthenticatedCreditsCardsIndexRoute,
  AuthenticatedCreditsIndexRoute: AuthenticatedCreditsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedLockersIndexRoute: AuthenticatedLockersIndexRoute,
  AuthenticatedMembershipsIndexRoute: AuthenticatedMembershipsIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedPromosIndexRoute: AuthenticatedPromosIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedTopupsIndexRoute: AuthenticatedTopupsIndexRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
